// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $('#save-button').click(function() {
      chrome.tabs.executeScript(null, {
        file: 'jquery.js'
      });
      chrome.tabs.executeScript(null, {
        file: 'save.js'
      });
      return window.close();
    });
    return $('#restore-button').click(function() {
      chrome.tabs.executeScript(null, {
        file: 'jquery.js'
      });
      chrome.tabs.executeScript(null, {
        file: 'restore.js'
      });
      return window.close();
    });
  });

}).call(this);
