// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var data, i, input, inputs, key, name, saved, savedData, savedInputs, savedSelects, savedTexts, select, selects, textarea, texts, url, val, _i, _j, _len, _len1, _ref, _ref1, _ref2, _results;

    url = window.location.pathname;
    key = 'formSaveAndRestore';
    data = localStorage.getItem(key);
    if (!data) {
      return;
    }
    savedData = JSON.parse(data);
    if (!savedData[url]) {
      return;
    }
    saved = savedData[url];
    _ref = saved.inputs;
    for (name in _ref) {
      savedInputs = _ref[name];
      inputs = $('input[name="' + name + '"]');
      i = 0;
      for (_i = 0, _len = inputs.length; _i < _len; _i++) {
        input = inputs[_i];
        ++i;
        if (i in savedInputs) {
          val = savedInputs[i];
          switch ($(input).attr('type')) {
            case 'checkbox':
            case 'radio':
              $(input).prop('checked', val === 'checked').change();
              break;
            case 'text':
            case 'password':
            case 'date':
            case 'datetime':
            case 'datetime-local':
            case 'email':
            case 'color':
            case 'month':
            case 'number':
            case 'range':
            case 'tel':
            case 'url':
            case 'week':
              $(input).val(val).change();
          }
        }
      }
    }
    _ref1 = saved.texts;
    for (name in _ref1) {
      savedTexts = _ref1[name];
      texts = $('textarea[name="' + name + '"]');
      i = 0;
      for (_j = 0, _len1 = texts.length; _j < _len1; _j++) {
        textarea = texts[_j];
        ++i;
        if (i in savedTexts) {
          $(textarea).val(savedTexts[i]).change();
        }
      }
    }
    _ref2 = saved.selects;
    _results = [];
    for (name in _ref2) {
      savedSelects = _ref2[name];
      selects = $('select[name="' + name + '"]');
      i = 0;
      _results.push((function() {
        var _k, _len2, _results1;

        _results1 = [];
        for (_k = 0, _len2 = selects.length; _k < _len2; _k++) {
          select = selects[_k];
          ++i;
          if (i in savedSelects) {
            _results1.push($(select).val(savedSelects[i]).change());
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      })());
    }
    return _results;
  });

}).call(this);
