// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var $input, i, input, inputData, j, k, option, optionData, taData, textarea, type, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2, _results;
    inputData = JSON.parse(localStorage.getItem('inputData'));
    taData = JSON.parse(localStorage.getItem('taData'));
    optionData = JSON.parse(localStorage.getItem('optionData'));
    i = 0;
    _ref = $('input');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      input = _ref[_i];
      $input = $(input);
      if (inputData[i] === null) {
        i++;
        continue;
      }
      type = $input.attr('type');
      switch (type) {
        case 'text':
        case 'password':
          $input.val(inputData[i]).change();
          break;
        case 'checkbox':
        case 'radio':
          $input.attr('checked', 'checked').change();
      }
      i++;
    }
    j = 0;
    _ref1 = $('textarea');
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      textarea = _ref1[_j];
      $(textarea).val(taData[j]).change();
      j++;
    }
    k = 0;
    _ref2 = $('option');
    _results = [];
    for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
      option = _ref2[_k];
      if (optionData[k] !== null) {
        $(option).attr('selected', 'selected').change();
      }
      _results.push(k++);
    }
    return _results;
  });

}).call(this);
