// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var $input, i, input, inputData, j, k, option, optionData, taData, textarea, type, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;
    inputData = [];
    i = 0;
    _ref = $('input');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      input = _ref[_i];
      $input = $(input);
      type = $input.attr('type');
      switch (type) {
        case 'text':
        case 'password':
          if ($input.val() !== '') {
            inputData[i] = $input.val();
          }
          break;
        case 'checkbox':
        case 'radio':
          if ($input.is(':checked')) {
            inputData[i] = 'checked';
          }
      }
      i += 1;
    }
    taData = [];
    j = 0;
    _ref1 = $('textarea');
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      textarea = _ref1[_j];
      taData[j] = $(textarea).val();
      j += 1;
    }
    optionData = [];
    k = 0;
    _ref2 = $('option');
    for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
      option = _ref2[_k];
      if ($(option).is(':selected')) {
        optionData[k] = 'selected';
      }
      k++;
    }
    localStorage.setItem('inputData', JSON.stringify(inputData));
    localStorage.setItem('taData', JSON.stringify(taData));
    return localStorage.setItem('optionData', JSON.stringify(optionData));
  });

}).call(this);
